# Generated by Django 6.0.7 on 2026-07-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cropsdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cropname', models.CharField(max_length=500)),
                ('season', models.CharField(max_length=500)),
                ('soiltype', models.CharField(max_length=500)),
                ('sowingmonth', models.CharField(max_length=500)),
                ('harvestingmonth', models.CharField(max_length=500)),
                ('fertilize', models.CharField(max_length=500)),
                ('disease', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='crops/')),
            ],
        ),
    ]
