# Generated by Django 6.0.7 on 2026-07-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropsdetail',
            old_name='image',
            new_name='c',
        ),
    ]
