# Generated by Django 6.0.7 on 2026-07-13 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0002_rename_image_cropsdetail_c'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropsdetail',
            old_name='c',
            new_name='crops',
        ),
    ]
