# Generated by Django 6.0.7 on 2026-07-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0003_rename_c_cropsdetail_crops'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cropname', models.CharField(max_length=500)),
                ('Marketname', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=500)),
            ],
        ),
    ]
