# Generated by Django 6.0.7 on 2026-07-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0004_market_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('village', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('problem', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='cropsdetail',
            name='crops',
            field=models.ImageField(upload_to=''),
        ),
    ]
