# Generated by Django 6.0.7 on 2026-07-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0006_government'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer_training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=10)),
                ('village', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('crop_detail', models.CharField(max_length=500)),
            ],
        ),
    ]
