# Generated by Django 6.0.7 on 2026-07-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0007_farmer_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsupdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=500)),
                ('posted_date', models.DateField()),
            ],
        ),
    ]
